version: "3.3"
services:
  parity:
    image: parity/parity:v2.0.9
    ports:
      - 21000:21000
      - 30303:30303
      - 8545:8545
    command: >
               --jsonrpc-apis personal,eth
               --chain dev
               --ws-interface all
               --jsonrpc-interface all
               --base-path /root/parity
               --no-ancient-blocks
               --no-serve-light
               --max-peers 250
               --snapshot-peers 50
               --min-peers 50
               --mode active
               --tracing off
               --pruning fast
               --allow-ips public
               --db-compaction ssd
               --cache-size 4096
               --ws-origins all
               --ws-hosts all
               --ws-port 21000
               --auto-update none
    volumes:
      - ./parity:/root/parity
    working_dir: /root/parity
    entrypoint: /home/parity/bin/parity
    user: root

  django:
    command: /bin/sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 8000"
    image: python:3.6
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 8000:8000

  node:
    command: /bin/sh -c "npm i && npm start"
    image: node:8.15
    working_dir: /code
    volumes:
      - ./web:/code
    ports:
      - 3000:3000
volumes:
  parity:
    external:
      name: parity