version: "3.3"
services:
  parity:
    image: parity/parity:v2.0.9
    ports:
      - 21000:21000
      - 30303:30303
    command: >
               --ws-interface all
               --jsonrpc-interface all
               --base-path /root/parity
               --no-ancient-blocks
               --no-serve-light
               --max-peers 250
               --snapshot-peers 50
               --min-peers 50
               --mode active
               --tracing off
               --pruning fast
               --allow-ips public
               --db-compaction ssd
               --cache-size 4096
               --ws-origins all
               --ws-hosts all
               --ws-port 21000
               --auto-update none
    volumes:
      - parity:/root/parity
    working_dir: /root/parity
    entrypoint: /home/parity/bin/parity
    user: root
volumes:
  parity:
    external:
      name: parity