# Generated by Django 2.1.4 on 2018-12-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(choices=[(transaction.models.BuySell('buy'), 'buy'), (transaction.models.BuySell('sell'), 'sell')])),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.TextField(choices=[(transaction.models.StatusChoices('open'), 'open'), (transaction.models.StatusChoices('closed'), 'closed')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_transaction', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.WaterRequest')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
