# Generated by Django 2.1.4 on 2019-01-11 17:42

from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrequest',
            name='status',
            field=models.TextField(choices=[(transaction.models.StatusChoices('open'), 'open'), (transaction.models.StatusChoices('closed'), 'closed')], default='open'),
        ),
    ]
