# Generated by Django 2.1.4 on 2019-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='liter_per_second',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purpose',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='address_off',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='address_on',
            field=models.TextField(null=True),
        ),
    ]
