# Generated by Django 2.1.4 on 2019-01-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
